version: '3.7'

services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - LICHESS_TOKEN=${LICHESS_TOKEN}
      - LICHESS_USERNAME=${LICHESS_USERNAME}
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      influxdb:
        condition: service_healthy
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

  populate_and_update:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: populate_and_update
    environment:
      - LICHESS_TOKEN=${LICHESS_TOKEN}
      - LICHESS_USERNAME=${LICHESS_USERNAME}
      - INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
    volumes:
      - ./populate-and-update-influxdb.py:/app/populate-and-update-influxdb.py
      - ./example.env:/app/.env
    working_dir: /app
    command: ["python3", "populate-and-update-influxdb.py"]
    depends_on:
      - influxdb
volumes:
  influxdb-data:
  grafana-data:
